"""Update Plant model

Revision ID: 0970a9764ea5
Revises: 632b22aee0a7
Create Date: 2024-07-04 14:03:13.259482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0970a9764ea5'
down_revision = '632b22aee0a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(),
               type_=sa.Numeric(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
